export const artists = [
  // 🎤 Singers
  { id: 1, name: "Aarav Kapoor", category: "Singer", location: "Mumbai", image: "/images/artists/singer1.jpg", tagline: "Bollywood playback singer with 100+ shows", priceRange: "₹50K – ₹1L", rating: 4.9, reviews: 120 },
  { id: 2, name: "Riya Sharma", category: "Singer", location: "Delhi", image: "/images/artists/singer2.jpg", tagline: "Soulful Sufi and acoustic performer", priceRange: "₹35K – ₹70K", rating: 4.8, reviews: 98 },
  { id: 3, name: "Kabir Mehta", category: "Singer", location: "Pune", image: "/images/artists/singer3.jpg", tagline: "Indie pop artist with viral hits", priceRange: "₹40K – ₹85K", rating: 4.7, reviews: 76 },
  { id: 4, name: "Sneha Iyer", category: "Singer", location: "Chennai", image: "/images/artists/singer4.jpg", tagline: "Carnatic vocalist and fusion performer", priceRange: "₹30K – ₹60K", rating: 4.9, reviews: 88 },
  { id: 5, name: "Dev Arora", category: "Singer", location: "Bangalore", image: "/images/artists/singer5.jpg", tagline: "Performs unplugged Bollywood sets", priceRange: "₹45K – ₹90K", rating: 4.8, reviews: 91 },
  { id: 6, name: "Meera Joshi", category: "Singer", location: "Kolkata", image: "/images/artists/singer6.jpg", tagline: "Sings retro and golden era classics", priceRange: "₹25K – ₹55K", rating: 4.6, reviews: 64 },
  { id: 7, name: "Zaid Khan", category: "Singer", location: "Hyderabad", image: "/images/artists/singer7.jpg", tagline: "Performs Sufi rock and fusion", priceRange: "₹50K – ₹1L", rating: 4.9, reviews: 102 },
  { id: 8, name: "Ananya Desai", category: "Singer", location: "Ahmedabad", image: "/images/artists/singer8.jpg", tagline: "Performs at weddings and private gigs", priceRange: "₹35K – ₹75K", rating: 4.7, reviews: 70 },
  { id: 9, name: "Raghav Nair", category: "Singer", location: "Goa", image: "/images/artists/singer9.jpg", tagline: "Performs beachside acoustic sets", priceRange: "₹30K – ₹65K", rating: 4.8, reviews: 58 },
  { id: 10, name: "Ishita Roy", category: "Singer", location: "Lucknow", image: "/images/artists/singer10.jpg", tagline: "Performs devotional and folk music", priceRange: "₹20K – ₹50K", rating: 4.6, reviews: 49 },

  // 🎧 DJs
  { id: 11, name: "DJ Arjun", category: "DJ", location: "Bangalore", image: "/images/artists/dj1.jpg", tagline: "Club & wedding DJ with EDM vibes", priceRange: "₹40K – ₹90K", rating: 4.7, reviews: 85 },
  { id: 12, name: "DJ Meera", category: "DJ", location: "Pune", image: "/images/artists/dj2.jpg", tagline: "Bollywood + Techno fusion sets", priceRange: "₹30K – ₹75K", rating: 4.9, reviews: 102 },
  { id: 13, name: "DJ Rishi", category: "DJ", location: "Delhi", image: "/images/artists/dj3.jpg", tagline: "Performs at college fests and clubs", priceRange: "₹35K – ₹80K", rating: 4.8, reviews: 67 },
  { id: 14, name: "DJ Tanya", category: "DJ", location: "Mumbai", image: "/images/artists/dj4.jpg", tagline: "House and trance specialist", priceRange: "₹45K – ₹95K", rating: 4.9, reviews: 74 },
  { id: 15, name: "DJ Karan", category: "DJ", location: "Chandigarh", image: "/images/artists/dj5.jpg", tagline: "Punjabi beats and dhol remixes", priceRange: "₹30K – ₹70K", rating: 4.6, reviews: 59 },
  { id: 16, name: "DJ Ayesha", category: "DJ", location: "Hyderabad", image: "/images/artists/dj6.jpg", tagline: "Performs at destination weddings", priceRange: "₹50K – ₹1L", rating: 4.8, reviews: 81 },
  { id: 17, name: "DJ Neil", category: "DJ", location: "Goa", image: "/images/artists/dj7.jpg", tagline: "Beach party and sunset sets", priceRange: "₹40K – ₹85K", rating: 4.7, reviews: 66 },
  { id: 18, name: "DJ Rhea", category: "DJ", location: "Kolkata", image: "/images/artists/dj8.jpg", tagline: "Performs Bollywood mashups", priceRange: "₹35K – ₹75K", rating: 4.6, reviews: 52 },
  { id: 19, name: "DJ Aman", category: "DJ", location: "Jaipur", image: "/images/artists/dj9.jpg", tagline: "Performs at corporate events", priceRange: "₹30K – ₹65K", rating: 4.5, reviews: 48 },
  { id: 20, name: "DJ Simran", category: "DJ", location: "Ahmedabad", image: "/images/artists/dj10.jpg", tagline: "Performs retro and 90s sets", priceRange: "₹25K – ₹60K", rating: 4.7, reviews: 50 },

  // 💃 Dancers
  { id: 21, name: "Nisha Rao", category: "Dancer", location: "Chennai", image: "/images/artists/dancer1.jpg", tagline: "Classical Bharatanatyam performer", priceRange: "₹25K – ₹60K", rating: 4.8, reviews: 64 },
  { id: 22, name: "Kabir Singh", category: "Dancer", location: "Delhi", image: "/images/artists/dancer2.jpg", tagline: "Hip-hop and freestyle choreographer", priceRange: "₹30K – ₹70K", rating: 4.7, reviews: 58 },
  { id: 23, name: "Aanya Pillai", category: "Dancer", location: "Mumbai", image: "/images/artists/dancer3.jpg", tagline: "Performs Bollywood and semi-classical", priceRange: "₹35K – ₹75K", rating: 4.9, reviews: 82 },
  { id: 24, name: "Rohan Das", category: "Dancer", location: "Bangalore", image: "/images/artists/dancer4.jpg", tagline: "Performs contemporary and lyrical", priceRange: "₹30K – ₹65K", rating: 4.6, reviews: 49 },
  { id: 25, name: "Simran Kaur", category: "Dancer", location: "Amritsar", image: "/images/artists/dancer5.jpg", tagline: "Punjabi folk and Bhangra expert", priceRange: "₹25K – ₹55K", rating: 4.7, reviews: 53 },
  { id: 26, name: "Zoya Sheikh", category: "Dancer", location: "Hyderabad", image: "/images/artists/dancer6.jpg", tagline: "Performs fusion and belly dance", priceRange: "₹40K – ₹85K", rating: 4.8, reviews: 66 },
  { id: 27, name: "Aditya Nair", category: "Dancer", location: "Kochi", image: "/images/artists/dancer7.jpg", tagline: "Performs cinematic and stage shows", priceRange: "₹35K – ₹70K", rating: 4.6, reviews: 47 },
  { id: 28, name: "Priya Verma", category: "Dancer", location: "Lucknow", image: "/images/artists/dancer8.jpg", tagline: "Kathak performer and instructor", priceRange: "₹30K – ₹60K", rating: 4.9, reviews: 61 },
  { id: 29, name: "Rahul Jain", category: "Dancer", location: "Indore", image: "/images/artists/dancer9.jpg", tagline: "Performs at college and cultural fests", priceRange: "₹25K – ₹50K", rating: 4.5, reviews: 42 },
  { id: 30, name: "Tanya Bhatt", category: "Dancer", location: "Jaipur", image: "/images/artists/dancer10.jpg", tagline: "Performs Lavani and folk fusion", priceRange: "₹30K – ₹65K", rating: 4.7, reviews: 56 },

  // 🎭 Comedians
  { id: 31, name: "Sana Qureshi", category: "Comedian", location: "Mumbai", image: "/images/artists/comedian1.jpg", tagline: "Stand-up comic with viral reels", priceRange: "₹40K – ₹85K", rating: 4.9, reviews: 91 },
  { id: 32, name: "Rohan Desai", category: "Comedian", location: "Ahmedabad", image: "/images/artists/comedian2.jpg", tagline: "Observational humor with a Gujarati twist", priceRange: "₹35K – ₹80K", rating: 4.8, reviews: 77 },
  { id: 33, name: "Neeti Sharma", category: "Comedian", location: "Delhi", image: "/images/artists/comedian3.jpg", tagline: "Performs at corporate and college gigs", priceRange: "₹30K – ₹70K", rating: 4.7, reviews: 63 },
  { id: 34, name: "Aman Khan", category: "Comedian", location: "Hyderabad", image: "/images/artists/comedian4.jpg", tagline: "Performs mimicry and character comedy", priceRange: "₹25K – ₹60K", rating: 4.6, reviews: 52 },
  { id: 35, name: "Divya Patel", category: "Comedian", location: "Pune", image: "/images/artists/comedian5.jpg", tagline: "Performs satire and social commentary", priceRange: "₹40K – ₹90K", rating: 4.8, reviews: 68 },
  { id: 36, name: "Kunal Rao", category: "Comedian", location: "Bangalore", image: "/images/artists/comedian6.jpg", tagline: "Performs clean comedy for families", priceRange: "₹35K – ₹75K", rating: 4.7, reviews: 59 },
  { id: 37, name: "Isha Malhotra", category: "Comedian", location: "Chandigarh", image: "/images/artists/comedian7.jpg", tagline: "Performs Punjabi stand-up and sketches", priceRange: "₹30K – ₹65K", rating: 4.6, reviews: 48 },
  { id: 38, name: "Nikhil Joshi", category: "Comedian", location: "Kolkata", image: "/images/artists/comedian8.jpg", tagline: "Performs bilingual comedy sets", priceRange: "₹25K – ₹55K", rating: 4.5, reviews: 44 },
  { id: 39, name: "Aarti Singh", category: "Comedian", location: "Lucknow", image: "/images/artists/comedian9.jpg", tagline: "Performs observational and family humor", priceRange: "₹30K – ₹60K", rating: 4.7, reviews: 51 },
  { id: 40, name: "Dev Mehta", category: "Comedian", location: "Jaipur", image: "/images/artists/comedian10.jpg", tagline: "Performs improv and crowd work", priceRange: "₹35K – ₹70K", rating: 4.8, reviews: 57 },

    // 📸 Influencers
  { id: 41, name: "Tanya Bhatia", category: "Influencer", location: "Delhi", image: "/images/artists/influencer1.jpg", tagline: "Fashion & lifestyle creator with 500K+ followers", priceRange: "₹60K – ₹1.2L", rating: 5.0, reviews: 110 },
  { id: 42, name: "Kunal Mehta", category: "Influencer", location: "Mumbai", image: "/images/artists/influencer2.jpg", tagline: "Tech reviewer & gadget guru", priceRange: "₹45K – ₹90K", rating: 4.9, reviews: 88 },
  { id: 43, name: "Rhea Kapoor", category: "Influencer", location: "Bangalore", image: "/images/artists/influencer3.jpg", tagline: "Beauty influencer with viral tutorials", priceRange: "₹50K – ₹1L", rating: 4.8, reviews: 76 },
  { id: 44, name: "Aman Verma", category: "Influencer", location: "Hyderabad", image: "/images/artists/influencer4.jpg", tagline: "Fitness coach and wellness vlogger", priceRange: "₹40K – ₹85K", rating: 4.7, reviews: 64 },
  { id: 45, name: "Simran Ahuja", category: "Influencer", location: "Chandigarh", image: "/images/artists/influencer5.jpg", tagline: "Travel vlogger with 100+ destinations", priceRange: "₹55K – ₹1.1L", rating: 4.9, reviews: 92 },
  { id: 46, name: "Devika Rao", category: "Influencer", location: "Pune", image: "/images/artists/influencer6.jpg", tagline: "Food blogger and recipe creator", priceRange: "₹35K – ₹75K", rating: 4.6, reviews: 58 },
  { id: 47, name: "Rajat Singh", category: "Influencer", location: "Kolkata", image: "/images/artists/influencer7.jpg", tagline: "Comedy reels and skits creator", priceRange: "₹30K – ₹65K", rating: 4.7, reviews: 61 },
  { id: 48, name: "Isha Malhotra", category: "Influencer", location: "Ahmedabad", image: "/images/artists/influencer8.jpg", tagline: "Parenting and lifestyle influencer", priceRange: "₹40K – ₹80K", rating: 4.8, reviews: 69 },
  { id: 49, name: "Nikhil Joshi", category: "Influencer", location: "Goa", image: "/images/artists/influencer9.jpg", tagline: "Adventure and outdoor content creator", priceRange: "₹45K – ₹95K", rating: 4.9, reviews: 73 },
  { id: 50, name: "Aarti Sharma", category: "Influencer", location: "Jaipur", image: "/images/artists/influencer10.jpg", tagline: "Sustainable living and eco tips", priceRange: "₹35K – ₹70K", rating: 4.6, reviews: 54 },

  // 🎤 Anchors
  { id: 51, name: "Neha Joshi", category: "Anchor", location: "Hyderabad", image: "/images/artists/anchor1.jpg", tagline: "Corporate & wedding anchor with 300+ events", priceRange: "₹30K – ₹65K", rating: 4.8, reviews: 72 },
  { id: 52, name: "Rajat Khurana", category: "Anchor", location: "Delhi", image: "/images/artists/anchor2.jpg", tagline: "TV host & live event specialist", priceRange: "₹40K – ₹85K", rating: 4.9, reviews: 95 },
  { id: 53, name: "Anjali Mehta", category: "Anchor", location: "Mumbai", image: "/images/artists/anchor3.jpg", tagline: "Performs at fashion shows and launches", priceRange: "₹35K – ₹75K", rating: 4.7, reviews: 63 },
  { id: 54, name: "Karan Desai", category: "Anchor", location: "Pune", image: "/images/artists/anchor4.jpg", tagline: "Corporate emcee and product launch host", priceRange: "₹30K – ₹70K", rating: 4.6, reviews: 58 },
  { id: 55, name: "Simran Kapoor", category: "Anchor", location: "Chennai", image: "/images/artists/anchor5.jpg", tagline: "Performs at weddings and sangeet nights", priceRange: "₹25K – ₹60K", rating: 4.8, reviews: 66 },
  { id: 56, name: "Amit Sharma", category: "Anchor", location: "Bangalore", image: "/images/artists/anchor6.jpg", tagline: "Performs at college fests and award shows", priceRange: "₹35K – ₹80K", rating: 4.7, reviews: 59 },
  { id: 57, name: "Tanya Verma", category: "Anchor", location: "Kolkata", image: "/images/artists/anchor7.jpg", tagline: "Performs bilingual anchoring (Hindi/English)", priceRange: "₹30K – ₹65K", rating: 4.6, reviews: 52 },
  { id: 58, name: "Rohan Iyer", category: "Anchor", location: "Ahmedabad", image: "/images/artists/anchor8.jpg", tagline: "Performs at tech expos and summits", priceRange: "₹40K – ₹90K", rating: 4.9, reviews: 71 },
  { id: 59, name: "Divya Rao", category: "Anchor", location: "Lucknow", image: "/images/artists/anchor9.jpg", tagline: "Performs at cultural and festive events", priceRange: "₹25K – ₹55K", rating: 4.5, reviews: 47 },
  { id: 60, name: "Nikhil Bhatia", category: "Anchor", location: "Jaipur", image: "/images/artists/anchor10.jpg", tagline: "Performs at sports and entertainment shows", priceRange: "₹35K – ₹70K", rating: 4.7, reviews: 53 },

    // 🧠 Motivational Speakers
  { id: 61, name: "Dr. Kavita Rao", category: "Motivational Speaker", location: "Pune", image: "/images/artists/speaker1.jpg", tagline: "TEDx speaker on mental resilience", priceRange: "₹50K – ₹1L", rating: 5.0, reviews: 60 },
  { id: 62, name: "Ankit Sharma", category: "Motivational Speaker", location: "Jaipur", image: "/images/artists/speaker2.jpg", tagline: "Youth mentor & leadership coach", priceRange: "₹35K – ₹75K", rating: 4.8, reviews: 48 },
  { id: 63, name: "Riya Malhotra", category: "Motivational Speaker", location: "Delhi", image: "/images/artists/speaker3.jpg", tagline: "Women empowerment and career growth", priceRange: "₹40K – ₹85K", rating: 4.9, reviews: 54 },
  { id: 64, name: "Siddharth Verma", category: "Motivational Speaker", location: "Mumbai", image: "/images/artists/speaker4.jpg", tagline: "Startup coach and business strategist", priceRange: "₹45K – ₹95K", rating: 4.7, reviews: 51 },
  { id: 65, name: "Neha Bansal", category: "Motivational Speaker", location: "Chandigarh", image: "/images/artists/speaker5.jpg", tagline: "Mental health advocate and counselor", priceRange: "₹30K – ₹70K", rating: 4.8, reviews: 49 },
  { id: 66, name: "Amitabh Joshi", category: "Motivational Speaker", location: "Bangalore", image: "/images/artists/speaker6.jpg", tagline: "Corporate trainer and keynote speaker", priceRange: "₹50K – ₹1.1L", rating: 4.9, reviews: 63 },
  { id: 67, name: "Tanya Desai", category: "Motivational Speaker", location: "Hyderabad", image: "/images/artists/speaker7.jpg", tagline: "Performs at youth summits and TEDx", priceRange: "₹35K – ₹80K", rating: 4.6, reviews: 44 },
  { id: 68, name: "Raghav Kapoor", category: "Motivational Speaker", location: "Ahmedabad", image: "/images/artists/speaker8.jpg", tagline: "Performs at colleges and leadership camps", priceRange: "₹30K – ₹65K", rating: 4.7, reviews: 46 },
  { id: 69, name: "Ishita Sen", category: "Motivational Speaker", location: "Kolkata", image: "/images/artists/speaker9.jpg", tagline: "Performs on self-growth and confidence", priceRange: "₹25K – ₹60K", rating: 4.6, reviews: 42 },
  { id: 70, name: "Dev Mehra", category: "Motivational Speaker", location: "Lucknow", image: "/images/artists/speaker10.jpg", tagline: "Performs on productivity and mindset", priceRange: "₹30K – ₹70K", rating: 4.8, reviews: 50 },

  // 🏅 Sports
  { id: 71, name: "Vikram Shetty", category: "Sports", location: "Chennai", image: "/images/artists/sports1.jpg", tagline: "Professional cricket coach & event guest", priceRange: "₹35K – ₹75K", rating: 4.9, reviews: 58 },
  { id: 72, name: "Anjali Rao", category: "Sports", location: "Delhi", image: "/images/artists/sports2.jpg", tagline: "Olympic-level gymnast & workshop host", priceRange: "₹40K – ₹85K", rating: 5.0, reviews: 41 },
  { id: 73, name: "Rohan Malhotra", category: "Sports", location: "Mumbai", image: "/images/artists/sports3.jpg", tagline: "Footballer and fitness influencer", priceRange: "₹30K – ₹65K", rating: 4.7, reviews: 52 },
  { id: 74, name: "Simran Kaur", category: "Sports", location: "Pune", image: "/images/artists/sports4.jpg", tagline: "National-level badminton player", priceRange: "₹35K – ₹70K", rating: 4.8, reviews: 47 },
  { id: 75, name: "Amit Desai", category: "Sports", location: "Bangalore", image: "/images/artists/sports5.jpg", tagline: "Performs at sports clinics and panels", priceRange: "₹40K – ₹90K", rating: 4.6, reviews: 43 },
  { id: 76, name: "Neha Sharma", category: "Sports", location: "Hyderabad", image: "/images/artists/sports6.jpg", tagline: "Performs at school and college events", priceRange: "₹25K – ₹55K", rating: 4.7, reviews: 39 },
  { id: 77, name: "Kunal Joshi", category: "Sports", location: "Ahmedabad", image: "/images/artists/sports7.jpg", tagline: "Performs at cricket leagues and expos", priceRange: "₹30K – ₹60K", rating: 4.5, reviews: 36 },
  { id: 78, name: "Divya Mehta", category: "Sports", location: "Kolkata", image: "/images/artists/sports8.jpg", tagline: "Performs at fitness and yoga retreats", priceRange: "₹35K – ₹75K", rating: 4.8, reviews: 45 },
  { id: 79, name: "Rajat Kapoor", category: "Sports", location: "Goa", image: "/images/artists/sports9.jpg", tagline: "Performs at beach sports and surf events", priceRange: "₹40K – ₹85K", rating: 4.9, reviews: 49 },
  { id: 80, name: "Isha Verma", category: "Sports", location: "Jaipur", image: "/images/artists/sports10.jpg", tagline: "Performs at marathons and fitness expos", priceRange: "₹30K – ₹65K", rating: 4.6, reviews: 42 },
];
